config/routes.rb
Githubdata::Application.routes.draw do
  get "pages/home"

  match '/demo', :to => 'pages#demo'

  match '/visualization', :to => 'pages#visualization', :as => 'visualization', :via => :post

  match '/times', :to => 'times#show', :as => 'times', :via => :post
  match '/times/select', :to => 'times#select', :as => 'select'

  match '/locations', :to => 'locations#show', :as => 'locations'

  resources :cities

  root :to => 'pages#home'

end

app/controllers/times_controller.rb
class TimesController < ApplicationController
  def select
    start_method = Time.now

    @date = parse_date(params[:date])
    @query = "#{params[:date]}"

    skip_parse = false
    if !Query.find_by_query_and_vis(@query,"times").nil?
      @lang_hours = retrieve_results(@query)
      skip_parse = true
    else
      @query_obj = Query.new(:query => @query, :vis => "times")
    end

    if !skip_parse
      @dataset = create_dataset(@date)

      @push_event_count = 0
      @lang_hours = {}

      start_query = Time.now

      require 'open-uri'
      require 'zlib'
      require 'yajl'

      @dataset.each do |datafile|
        puts "Checking #{datafile}."

        gz = open(datafile)
        js = Zlib::GzipReader.new(gz).read

        Yajl::Parser.parse(js) do |event|
          if event["type"] != "PushEvent"
            next
          else
            @push_event_count += 1
          end

          hour = DateTime.strptime(event["created_at"]).hour

          if event["repository"].nil? || event["repository"].empty?
            next
          end

          lang = event["repository"]["language"]

          if lang.nil? || lang == ""
            next
          end

          if @lang_hours[hour].nil?
            @lang_hours[hour] = {lang => 1}
          else
            if @lang_hours[hour][lang].nil?
              @lang_hours[hour][lang] = 0
            end
            @lang_hours[hour][lang] += 1
          end
        end
      end

      @date = generate_date(@date)

      @lang_hours.each do |hour, lang_hash|
        lang_hash.each do |lang, cnt|
          Results.create(:date => @date, :language => lang, :count => cnt, :hour => hour, :query => @query)
        end
      end

      finish_query = Time.now
      puts "query took #{finish_query-start_query} seconds for #{@push_event_count} events."
    end

    if @lang_hours.keys.length == 24 && !skip_parse
      @query_obj.save
    end

    @lang_hours, @available_languages = filter_values(@lang_hours,50) # only keep languages with counts > 100 for all hrs in @lang_hours with available data

    @available_languages = @available_languages.keys
    @select_languages = ""
    @available_languages.each do |lang|
      @select_languages << "<option>" << lang << "</option>"
    end

    session[:query] = @query

    finish_method = Time.now
    if Rails.env.development?
      puts "times#select took #{finish_method-start_method} seconds"
    end
  end

  def show
    start_method = Time.now

    @query = session[:query]
    @lang_hours = retrieve_results(@query)

    # @lang_hours = filter_count(@lang_hours, 100)
    @languages = params[:languages] #, "Java", "C", "PHP", "Python"]
    @lang_hours = filter_languages(@lang_hours, @languages)

    @lang_hours = normalize_values(@lang_hours)
    # @unique_languages = count_languages(@lang_hours)

    finish_method = Time.now
    if Rails.env.development?
      puts "times#show took #{finish_method-start_method} seconds"
    end
  end

  private
    def filter_values(results, bound) # Keep languages with number of events greater than input bound and with 24 hrs of data
      languages = Hash.new(0)
      results.each do |hour, lang_hash|
        lang_hash.keep_if { |lang, cnt| cnt > bound } # bound check
        lang_hash.keys.each do |lang|
          languages[lang] += 1
        end
      end
      results.each do |hour, lang_hash|
        lang_hash.keep_if { |lang, cnt| languages[lang] == 24 } # 24 hr check
      end
      languages.keep_if { |lang, hr_cnt| hr_cnt == 24 }
      return results, languages
    end

    def filter_languages(results, languages) # Keep languages specified by an array of allowed languages
      results.each do |hour, lang_hash|
        lang_hash.keep_if { |lang, cnt| languages.include?(lang) }
      end
      results
    end

    def normalize_values(results) # Normalize results of language events per hour
      @languages.each do |sel_lang|
        lang_max = 0
        results.each do |hour, lang_hash|
          lang_hash.each do |lang, cnt|
            if lang == sel_lang && cnt > lang_max
              lang_max = cnt
            end
          end
        end
        if Rails.env.development?
          puts "Lang #{sel_lang} max is #{lang_max}."
        end
        results.each do |hour, lang_hash|
          lang_hash.each do |lang, cnt|
            if lang == sel_lang
              lang_hash[lang] = cnt.to_f / lang_max.to_f
            end
          end
        end
      end
      results
    end

    def count_languages(values) # Count the number of unique languages
      uniques = []
      values.each do |hour, lang_hash|
        lang_hash.each do |lang, cnt|
          if !uniques.include?(lang)
            uniques << lang
          end
        end
      end
      uniques.count
    end

    def retrieve_results(query) 
      @return = {}

      results = Results.find_all_by_query(@query)
      results.each do |result|
        if @return[result.hour].nil?
          @return[result.hour] = {}
          @return[result.hour][result.language] = result.count
        else
          @return[result.hour][result.language] = result.count
        end
      end
      @return
    end

    def generate_date(date_hash)
      if date_hash[:hour]
        @gen_date = "#{date_hash[:year]}-#{date_hash[:month]}-#{date_hash[:day]}-#{date_hash[:hour]}"
      else
        @gen_date = "#{date_hash[:year]}-#{date_hash[:month]}-#{date_hash[:day]}"
      end
      @gen_date
    end

    def create_parser(date_field, parser_field, event_field)
      @new_parser = Parser.find_by_date_and_parser_type_and_event_type(
        date_field,
        parser_field,
        event_field)
      if @new_parser.nil?
        @new_parser = Parser.create(
          :date => date_field,
          :parser_type => parser_field,
          :event_type => event_field)
      end
      @new_parser
    end

end

app/helpers/times_helper.rb
module TimesHelper
	def init_skrollr
		javascript_tag "
			$(function() {
				var s = skrollr.init();
			});"
	end
	def check_selection
		javascript_tag "
			$(function() {
				$('#languages').click(
					function() { 
						var num_selected = $('#languages').val().length;
						var $warning = $('#warning');
						var $btn = $('.btn');
						if(num_selected > 5) {
							$warning.text('You can only select a maximum of five languages');
							$btn.attr('disabled','disabled');
						} else {
							$warning.text('');
							$btn.removeAttr('disabled');
						}
					});
				});"
	end
end

app/views/times/select.html.haml
%h1 Select Languages

= check_selection

%h1#warning

= form_tag times_path, :class => "form-horizontal" do
	.control-group
		= label_tag "languages", "Select five languages", :class => "control-label"
		.controls
			= select_tag "languages", @select_languages.html_safe, :multiple => true, :size => @available_languages.length
	.control-group
		.controls
			= submit_tag "Show", :class => "btn btn-warning"

app/views/times/show.html.haml
/ %h1 Times

= javascript_include_tag 'times'
= stylesheet_link_tag 'times'

.star#star1
.star#star2
.star#star3
.star#star4
.star#star5
.star#star6
.star#star7
.star#star8
.star#star9
.star#star10
.star#star11

#window{ "data-0" => "background-color:rgb(8,29,47);",
    "data-1200" => "background-color:rgb(58,166,208);",
    "data-2300" => "background-color:rgb(8,29,47);" }

#moon-am{ "data-0" => "left:50%;top:10%; background-color:rgb(255,255,255);",
    "data-100" => "left:40%;top:10%;",
    "data-200" => "left:30%;top:15%;",
    "data-300" => "left:20%;top:20%;",
    "data-400" => "left:10%;top:30%;",
    "data-500" => "left:00%;top:40%;",
    "data-600" => "left:-10%;top:70%;" }

#sun{ "data-0" => "right:-100%; top:100%; background-color:rgb(25,25,0);",
    "data-1200" => "right:50%; top:10%; background-color:rgb(255,206,20);",
    "data-2300" => "right:95%; top:100%; background-color:rgb(8,29,47);" }

#moon-pm{ "data-1700" => "left:100%;top:70%;",
    "data-1800" => "left:100%;top:40%;",
    "data-1900" => "left:90%;top:30%;",
    "data-2000" => "left:80%;top:20%;",
    "data-2100" => "left:70%;top:15%;",
    "data-2200" => "left:60%;top:10%;",
    "data-2300" => "left:50%;top:10%;" }

.wrapped
	.chart-row
		- @languages.each do |lang|
			.language.span1
				#{lang}
				.bar{ :id => "lang-bar",
							"data-0" => "transform:scale(1,#{@lang_hours[0][lang]})",
							"data-100" => "transform:scale(1,#{@lang_hours[1][lang]})",
							"data-200" => "transform:scale(1,#{@lang_hours[2][lang]})",
							"data-300" => "transform:scale(1,#{@lang_hours[3][lang]})",
							"data-400" => "transform:scale(1,#{@lang_hours[4][lang]})",
							"data-500" => "transform:scale(1,#{@lang_hours[5][lang]})",
							"data-600" => "transform:scale(1,#{@lang_hours[6][lang]})",
							"data-700" => "transform:scale(1,#{@lang_hours[7][lang]})",
							"data-800" => "transform:scale(1,#{@lang_hours[8][lang]})",
							"data-900" => "transform:scale(1,#{@lang_hours[9][lang]})",
							"data-1000" => "transform:scale(1,#{@lang_hours[10][lang]})",
							"data-1100" => "transform:scale(1,#{@lang_hours[11][lang]})",
							"data-1200" => "transform:scale(1,#{@lang_hours[12][lang]})",
							"data-1300" => "transform:scale(1,#{@lang_hours[13][lang]})",
							"data-1400" => "transform:scale(1,#{@lang_hours[14][lang]})",
							"data-1500" => "transform:scale(1,#{@lang_hours[15][lang]})",
							"data-1600" => "transform:scale(1,#{@lang_hours[16][lang]})",
							"data-1700" => "transform:scale(1,#{@lang_hours[17][lang]})",
							"data-1800" => "transform:scale(1,#{@lang_hours[18][lang]})",
							"data-1900" => "transform:scale(1,#{@lang_hours[19][lang]})",
							"data-2000" => "transform:scale(1,#{@lang_hours[20][lang]})",
							"data-2100" => "transform:scale(1,#{@lang_hours[21][lang]})",
							"data-2200" => "transform:scale(1,#{@lang_hours[22][lang]})",
							"data-2300" => "transform:scale(1,#{@lang_hours[23][lang]})" }

/			.bar{ :id => "lang-bar",
/						"data-0" => "transform:scale(1,#{@lang_hours[0][lang]})",
/						"data-200" => "transform:scale(1,#{@lang_hours[1][lang]})",
/						"data-400" => "transform:scale(1,#{@lang_hours[2][lang]})",
/						"data-600" => "transform:scale(1,#{@lang_hours[3][lang]})",
/						"data-800" => "transform:scale(1,#{@lang_hours[4][lang]})",
/						"data-1000" => "transform:scale(1,#{@lang_hours[5][lang]})",
/						"data-1200" => "transform:scale(1,#{@lang_hours[6][lang]})",
/						"data-1400" => "transform:scale(1,#{@lang_hours[7][lang]})",
/						"data-1600" => "transform:scale(1,#{@lang_hours[8][lang]})",
/						"data-1800" => "transform:scale(1,#{@lang_hours[9][lang]})",
/						"data-2000" => "transform:scale(1,#{@lang_hours[10][lang]})",
/						"data-2200" => "transform:scale(1,#{@lang_hours[11][lang]})",
/						"data-2200" => "transform:scale(1,#{@lang_hours[12][lang]})",
/						"data-2400" => "transform:scale(1,#{@lang_hours[13][lang]})",
/						"data-2600" => "transform:scale(1,#{@lang_hours[14][lang]})",
/						"data-2800" => "transform:scale(1,#{@lang_hours[15][lang]})",
/						"data-3000" => "transform:scale(1,#{@lang_hours[16][lang]})",
/						"data-3200" => "transform:scale(1,#{@lang_hours[17][lang]})",
/						"data-3400" => "transform:scale(1,#{@lang_hours[18][lang]})",
/						"data-3600" => "transform:scale(1,#{@lang_hours[19][lang]})",
/						"data-3800" => "transform:scale(1,#{@lang_hours[20][lang]})",
/						"data-4000" => "transform:scale(1,#{@lang_hours[21][lang]})",
/						"data-4200" => "transform:scale(1,#{@lang_hours[22][lang]})",
/						"data-4400" => "transform:scale(1,#{@lang_hours[23][lang]})" }